'use client'

import { useEffect, useState } from 'react'

interface PricingClientProps {
  isPro: boolean
  generationsUsed: number
  hasStripeCustomer: boolean
  userId: string
}

// Stripe Payment Links (one-time credit packs).
// Override at build time with NEXT_PUBLIC_STRIPE_STARTER_URL / NEXT_PUBLIC_STRIPE_PRO_URL.
const STARTER_URL =
  process.env.NEXT_PUBLIC_STRIPE_STARTER_URL ||
  'https://buy.stripe.com/eVqdR95gFdLV4M3cF8gjC0l'
const PRO_URL =
  process.env.NEXT_PUBLIC_STRIPE_PRO_URL ||
  'https://buy.stripe.com/28E6oH7oNePZ92j20ugjC0m'

const STARTER_FEATURES = [
  '10 video credits',
  'Each video ~35 seconds',
  'MP4 ready to post',
  'Valid for 12 months',
  'Email support',
]

const PRO_FEATURES = [
  '25 video credits',
  'Everything in Starter',
  'Priority render queue',
  'Early access to new niches',
  'Valid for 12 months',
]

const FAQS = [
  {
    q: 'Do credits expire?',
    a: 'Purchased credits are valid for 12 months from the date of purchase.',
  },
  {
    q: 'What counts as 1 credit?',
    a: 'Each video generated by Autopilot uses 1 credit — including script, voice, visuals, captions, and rendering.',
  },
  {
    q: 'Is this a subscription?',
    a: 'No. These are one-time credit packs. No recurring charges, no surprises.',
  },
  {
    q: 'Can I get a refund?',
    a: 'Yes, within 7 days of purchase if no credits have been used. Email josephsskaf@gmail.com.',
  },
]

export default function PricingClient(props: PricingClientProps) {
  const { isPro, userId } = props
  const [credits, setCredits] = useState<number | null>(null)
  const [creditsLoading, setCreditsLoading] = useState(true)
  const [toast, setToast] = useState<string | null>(null)
  const [purchasing, setPurchasing] = useState<string | null>(null)
  const [portalLoading, setPortalLoading] = useState(false)

  useEffect(() => {
    let cancelled = false
    fetch('/api/credits', { cache: 'no-store' })
      .then((r) => r.json())
      .then((data) => {
        if (!cancelled) {
          setCredits(typeof data.credits === 'number' ? data.credits : 0)
        }
      })
      .catch(() => {
        if (!cancelled) setCredits(0)
      })
      .finally(() => {
        if (!cancelled) setCreditsLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [])

  function showToast(msg: string) {
    setToast(msg)
    setTimeout(() => setToast(null), 2800)
  }

  function handleBuy(pack: 'starter' | 'pro') {
    if (!userId) {
      showToast('Please sign in again to continue.')
      return
    }
    setPurchasing(pack)
    const base = pack === 'starter' ? STARTER_URL : PRO_URL
    // client_reference_id flows through to the webhook so we know whose credits to top up.
    const url = `${base}${base.includes('?') ? '&' : '?'}client_reference_id=${encodeURIComponent(userId)}`
    window.location.href = url
  }

  async function handlePortal() {
    setPortalLoading(true)
    try {
      const res = await fetch('/api/stripe/portal', { method: 'POST' })
      const data = await res.json()
      if (data?.url) window.location.href = data.url
    } catch {
      // ignore
    } finally {
      setPortalLoading(false)
    }
  }

  return (
    <div className="px-4 md:px-6 py-7 pb-20">
      {/* Toast */}
      {toast && (
        <div
          className="fixed bottom-6 left-1/2 z-50 px-5 py-3 rounded-xl text-sm font-bold text-white"
          style={{
            transform: 'translateX(-50%)',
            background: 'linear-gradient(135deg, #6366f1, #7c3aed)',
            boxShadow: '0 4px 24px rgba(99,102,241,.4)',
          }}
        >
          {toast}
        </div>
      )}

      {/* Header */}
      <div className="mb-8 text-center relative">
        <div
          className="absolute pointer-events-none"
          style={{
            width: 700, height: 400,
            background: 'radial-gradient(ellipse at 50% 50%, rgba(99,102,241,.12) 0%, transparent 70%)',
            top: -100, left: '50%', transform: 'translateX(-50%)',
          }}
        />
        <div className="relative z-10">
          <div className="font-black uppercase tracking-widest mb-2" style={{ fontSize: '0.62rem', color: 'var(--indigo-light)' }}>
            Buy video credits
          </div>
          <h1 className="font-black tracking-tight mb-2" style={{ fontSize: '1.9rem', color: 'var(--text)' }}>
            Pay only for what you use.{' '}
            <span
              style={{
                background: 'linear-gradient(135deg, #818cf8, #c4b5fd, #a855f7)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
              }}
            >
              No subscription.
            </span>
          </h1>
          <p style={{ fontSize: '0.95rem', color: 'var(--muted)', maxWidth: 480, margin: '0 auto' }}>
            One-time purchase. 1 credit = 1 Short ready to post.
          </p>
        </div>
      </div>

      {/* Current credits */}
      <div
        className="max-w-lg mx-auto mb-8 flex items-center gap-4 rounded-xl px-5 py-4"
        style={{
          background: 'rgba(99,102,241,.06)',
          border: '1px solid rgba(99,102,241,.18)',
        }}
      >
        <div className="text-2xl">⚡</div>
        <div className="flex-1">
          <p className="font-bold text-sm" style={{ color: 'var(--text)' }}>
            {creditsLoading ? 'Loading balance...' : `You have ${credits ?? 0} credit${credits === 1 ? '' : 's'}`}
          </p>
          <p className="text-xs" style={{ color: 'var(--muted)' }}>
            Each Short uses 1 credit.
          </p>
        </div>
        {isPro && (
          <button
            onClick={handlePortal}
            disabled={portalLoading}
            className="rounded-lg px-3 py-2 text-xs font-bold"
            style={{
              background: 'rgba(255,255,255,.04)',
              border: '1px solid var(--border2)',
              color: 'var(--muted2)',
              cursor: portalLoading ? 'not-allowed' : 'pointer',
              opacity: portalLoading ? 0.6 : 1,
            }}
          >
            ⚙️ Billing
          </button>
        )}
      </div>

      {/* 2 packs */}
      <div
        className="grid max-w-3xl mx-auto gap-5"
        style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))' }}
      >
        {/* Starter */}
        <div
          className="rounded-[20px] p-7 transition-all flex flex-col"
          style={{
            background: 'rgba(15,15,30,0.85)',
            border: '1px solid var(--border2)',
            boxShadow: '0 0 30px rgba(99,102,241,.06)',
          }}
        >
          <div className="mb-5">
            <div className="text-xs font-black uppercase tracking-widest mb-2" style={{ color: 'var(--muted)' }}>
              Starter Pack
            </div>
            <div className="flex items-end gap-1 mb-1">
              <span className="font-black" style={{ fontSize: '2.5rem', color: 'var(--text)', lineHeight: 1 }}>$9</span>
              <span className="text-sm pb-1" style={{ color: 'var(--muted)' }}>one-time</span>
            </div>
            <p className="text-xs" style={{ color: 'var(--muted)' }}>10 videos ready to post.</p>
          </div>

          <div className="flex flex-col gap-2.5 mb-7 flex-1">
            {STARTER_FEATURES.map((f) => (
              <div key={f} className="flex items-center gap-2.5 text-sm">
                <span style={{ color: '#34d399', fontSize: '0.8rem' }}>✓</span>
                <span style={{ color: 'var(--text2)' }}>{f}</span>
              </div>
            ))}
          </div>

          <button
            onClick={() => handleBuy('starter')}
            disabled={purchasing === 'starter'}
            className="w-full rounded-xl py-3.5 text-sm font-black text-white transition-all"
            style={{
              background: 'linear-gradient(135deg, var(--indigo), var(--purple))',
              boxShadow: '0 4px 22px rgba(99,102,241,.32)',
              border: 'none',
              cursor: purchasing === 'starter' ? 'wait' : 'pointer',
              opacity: purchasing === 'starter' ? 0.7 : 1,
            }}
          >
            {purchasing === 'starter' ? 'Loading...' : 'Buy 10 Credits — $9'}
          </button>
        </div>

        {/* Pro — Most Popular */}
        <div
          className="rounded-[20px] p-7 relative overflow-hidden transition-all flex flex-col"
          style={{
            background: 'linear-gradient(135deg, rgba(99,102,241,.10), rgba(124,58,237,.06))',
            border: '2px solid rgba(99,102,241,.45)',
            boxShadow: '0 0 60px rgba(99,102,241,.2)',
          }}
        >
          <div
            className="absolute top-4 right-4 px-2.5 py-1 rounded-full text-xs font-black"
            style={{ background: 'linear-gradient(135deg, var(--indigo), var(--purple))', color: 'white' }}
          >
            Most Popular
          </div>

          <div className="mb-5">
            <div className="text-xs font-black uppercase tracking-widest mb-2" style={{ color: 'var(--indigo-light)' }}>
              Pro Pack
            </div>
            <div className="flex items-end gap-1 mb-1">
              <span className="font-black" style={{ fontSize: '2.5rem', color: 'var(--text)', lineHeight: 1 }}>$19</span>
              <span className="text-sm pb-1" style={{ color: 'var(--muted)' }}>one-time</span>
            </div>
            <p className="text-xs" style={{ color: 'var(--muted)' }}>25 videos — best price per Short.</p>
          </div>

          <div className="flex flex-col gap-2.5 mb-7 flex-1">
            {PRO_FEATURES.map((f) => (
              <div key={f} className="flex items-center gap-2.5 text-sm">
                <span style={{ color: '#34d399', fontSize: '0.8rem' }}>✓</span>
                <span style={{ color: 'var(--text2)' }}>{f}</span>
              </div>
            ))}
          </div>

          <button
            onClick={() => handleBuy('pro')}
            disabled={purchasing === 'pro'}
            className="w-full rounded-xl py-3.5 text-sm font-black text-white transition-all"
            style={{
              background: 'linear-gradient(135deg, #6366f1 0%, #7c3aed 55%, #a855f7 100%)',
              boxShadow: '0 4px 28px rgba(99,102,241,.45)',
              border: 'none',
              cursor: purchasing === 'pro' ? 'wait' : 'pointer',
              opacity: purchasing === 'pro' ? 0.7 : 1,
            }}
          >
            {purchasing === 'pro' ? 'Loading...' : 'Buy 25 Credits — $19'}
          </button>
        </div>
      </div>

      <p className="max-w-3xl mx-auto text-center text-xs mt-4" style={{ color: 'var(--muted)' }}>
        One-time payment. No subscription. Refund within 7 days if unused.
      </p>

      {/* FAQ */}
      <div className="max-w-2xl mx-auto mt-12">
        <h2 className="font-black text-center mb-6 tracking-tight" style={{ fontSize: '1.1rem', color: 'var(--text)' }}>
          Frequently Asked Questions
        </h2>
        <div className="flex flex-col gap-3">
          {FAQS.map((faq) => (
            <div
              key={faq.q}
              className="rounded-xl px-5 py-4"
              style={{
                background: 'rgba(15,15,30,0.85)',
                border: '1px solid var(--border)',
                boxShadow: '0 0 30px rgba(139,92,246,.06)',
              }}
            >
              <p className="font-bold text-sm mb-1.5" style={{ color: 'var(--text)' }}>{faq.q}</p>
              <p className="text-xs leading-relaxed" style={{ color: 'var(--muted)' }}>{faq.a}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
