import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createClient as createSupabaseAdmin } from '@supabase/supabase-js'

export const dynamic = 'force-dynamic'

// Service-role client — bypasses RLS for the cross-row read/write (resolving
// another user's code and stamping the caller's referred_by). Same pattern as
// app/api/stripe/webhook/route.ts.
function getAdminClient() {
  return createSupabaseAdmin(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )
}

export async function POST(req: NextRequest) {
  try {
    // Auth via the normal SSR client.
    const supabase = createClient()
    const {
      data: { user },
    } = await supabase.auth.getUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    let body: { ref?: string }
    try {
      body = await req.json()
    } catch {
      return NextResponse.json({ ok: false }, { status: 400 })
    }
    const ref = (body.ref ?? '').trim().toUpperCase()
    if (!ref) return NextResponse.json({ ok: false })

    // Harden: accept only the exact alphabet/length generated by /api/referral.
    if (!/^[A-HJ-NP-Z2-9]{8}$/.test(ref)) {
      return NextResponse.json({ ok: false, reason: 'invalid_ref' })
    }

    const admin = getAdminClient()

    // Already attributed — no-op (first-touch wins, never overwrite).
    const { data: me, error: meError } = await admin
      .from('profiles')
      .select('id, referred_by')
      .eq('id', user.id)
      .maybeSingle()
    if (meError) {
      console.error('[referral attribute] profile load error:', meError.code, meError.message)
      return NextResponse.json({ ok: false, reason: 'profile_load_failed' })
    }
    if (!me) return NextResponse.json({ ok: false, reason: 'no_profile' })
    if (me.referred_by) {
      return NextResponse.json({ ok: true, already: true })
    }

    // Codes are stored normalized in uppercase, so an exact lookup is enough.
    const { data: referrer } = await admin
      .from('profiles')
      .select('id')
      .eq('referral_code', ref)
      .maybeSingle()
    if (!referrer) return NextResponse.json({ ok: false, reason: 'unknown_ref' })

    // No self-referral.
    if (referrer.id === user.id) return NextResponse.json({ ok: false, reason: 'self_referral' })

    // First-touch wins even under concurrent requests. Only an empty
    // referred_by can be updated; a racing request cannot overwrite it.
    const { data: attributed, error: updErr } = await admin
      .from('profiles')
      .update({ referred_by: referrer.id })
      .eq('id', user.id)
      .is('referred_by', null)
      .select('id')
      .maybeSingle()
    if (updErr) {
      console.error('[referral attribute] update error:', updErr.code, updErr.message)
      return NextResponse.json({ ok: false, reason: 'update_failed' })
    }
    if (attributed?.id) return NextResponse.json({ ok: true })

    // A concurrent first-touch may have won between the initial read and the
    // conditional update. Confirm it instead of reporting a false success.
    const { data: current, error: currentError } = await admin
      .from('profiles')
      .select('referred_by')
      .eq('id', user.id)
      .maybeSingle()
    if (currentError) {
      console.error('[referral attribute] reconciliation error:', currentError.code, currentError.message)
      return NextResponse.json({ ok: false, reason: 'reconciliation_failed' })
    }
    if (current?.referred_by) return NextResponse.json({ ok: true, already: true })

    return NextResponse.json({ ok: false, reason: 'not_attributed' })
  } catch (err) {
    console.error('[referral attribute] unexpected:', err)
    return NextResponse.json({ ok: false })
  }
}
