@echo off
cd /d "%~dp0"
echo Killing any git processes...
taskkill /f /im git.exe 2>nul
taskkill /f /im git-remote-https.exe 2>nul
taskkill /f /im ssh.exe 2>nul
echo Waiting 3 seconds...
ping -n 4 127.0.0.1 >nul
echo Deleting lock files...
del /f ".git\index.lock" 2>nul
del /f ".git\HEAD.lock" 2>nul
del /f ".git\refs\heads\main.lock" 2>nul
del /f ".git\packed-refs.lock" 2>nul
echo Waiting 2 more seconds...
ping -n 3 127.0.0.1 >nul
echo Adding files...
git add app/api/stripe/checkout/route.ts
echo Committing...
git commit -m "feat(#273): multi-currency (USD/BRL/INR), auto payment methods (UPI/PIX/card by country)"
echo Pushing...
git push origin main
echo Done!
pause
