// Push #116 — global footer for public marketing surfaces (/, /start,
// /pricing, /login, /signup, /terms, /privacy, /not-found). Stays out
// of (dashboard)/* so signed-in surfaces don't pick up duplicated
// chrome — the sidebar there already carries the legal pointers.
//
// Push #162 — rebuilt into a branded multi-column footer: logo mark +
// tagline, a Product column, a Legal column, and a bottom bar with the
// copyright and version. Server-rendered (no client hooks).

import Link from 'next/link'

const linkStyle: React.CSSProperties = {
  color: '#94A3B8',
  textDecoration: 'none',
  fontSize: 13,
  lineHeight: 2,
  transition: 'color 0.15s ease',
}

const headingStyle: React.CSSProperties = {
  color: '#F5F7FF',
  fontSize: 11,
  fontWeight: 800,
  letterSpacing: '0.08em',
  textTransform: 'uppercase',
  marginBottom: 8,
}

export default function Footer() {
  return (
    <footer
      style={{
        borderTop: '1px solid rgba(255,255,255,.06)',
        background: 'linear-gradient(180deg, transparent, rgba(11,16,32,.5))',
        marginTop: 40,
        color: '#94A3B8',
      }}
    >
      <div
        style={{
          maxWidth: 1100,
          margin: '0 auto',
          padding: '40px 20px 8px',
          display: 'grid',
          gridTemplateColumns: 'minmax(0, 1.4fr) repeat(2, minmax(0, 1fr))',
          gap: 32,
        }}
        className="sf-footer-grid"
      >
        {/* Brand block */}
        <div>
          <Link
            href="/"
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 10,
              textDecoration: 'none',
              marginBottom: 12,
            }}
          >
            <span
              style={{
                width: 34,
                height: 34,
                borderRadius: 10,
                background: '#151C2F',
                border: '1px solid rgba(59,130,246,0.4)',
                boxShadow: '0 0 16px rgba(34,211,238,0.3)',
                display: 'inline-flex',
                alignItems: 'center',
                justifyContent: 'center',
                flexShrink: 0,
              }}
            >
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                <path d="M13 2L3 14h7l-1 8 10-12h-7l1-8z" fill="#22D3EE" stroke="#3B82F6" strokeWidth="0.5" strokeLinejoin="round" />
              </svg>
            </span>
            <span style={{ fontWeight: 900, fontSize: '1.05rem', letterSpacing: '-0.01em' }}>
              <span style={{ color: '#F5F7FF' }}>ShortsForge</span>
              <span style={{ color: '#22D3EE' }}>AI</span>
            </span>
          </Link>
          <p style={{ fontSize: 13, lineHeight: 1.6, maxWidth: 300, color: '#94A3B8' }}>
            Turn any idea into a fully edited, viral-ready YouTube Short — script,
            voiceover, footage and captions, generated by AI in about a minute.
          </p>
        </div>

        {/* Product column */}
        <div>
          <div style={headingStyle}>Product</div>
          <nav style={{ display: 'flex', flexDirection: 'column' }}>
            <Link href="/generate" style={linkStyle}>Generate Video</Link>
            <Link href="/my-videos" style={linkStyle}>My Videos</Link>
            <Link href="/examples" style={linkStyle}>Examples</Link>
            <Link href="/pricing" style={linkStyle}>Pricing</Link>
          </nav>
        </div>

        {/* Legal column */}
        <div>
          <div style={headingStyle}>Company</div>
          <nav style={{ display: 'flex', flexDirection: 'column' }}>
            <Link href="/terms" style={linkStyle}>Terms of Service</Link>
            <Link href="/privacy" style={linkStyle}>Privacy Policy</Link>
            <a href="mailto:hello@shortsforgeai.com" style={linkStyle}>Contact</a>
          </nav>
        </div>
      </div>

      {/* Bottom bar */}
      <div
        style={{
          borderTop: '1px solid rgba(255,255,255,.05)',
          maxWidth: 1100,
          margin: '0 auto',
          padding: '14px 20px 22px',
          display: 'flex',
          flexWrap: 'wrap',
          gap: '6px 14px',
          alignItems: 'center',
          justifyContent: 'space-between',
          fontSize: 12,
        }}
      >
        <span style={{ fontWeight: 600 }}>© 2026 ShortsForgeAI · All rights reserved</span>
        <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, color: '#64748b' }}>
          <span
            aria-hidden
            style={{
              width: 6,
              height: 6,
              borderRadius: '50%',
              background: '#10b981',
              boxShadow: '0 0 6px rgba(16,185,129,.6)',
              display: 'inline-block',
            }}
          />
          Built for creators · v1.5
        </span>
      </div>

      <style>{`
        @media (max-width: 640px) {
          .sf-footer-grid {
            grid-template-columns: 1fr 1fr !important;
          }
          .sf-footer-grid > :first-child {
            grid-column: 1 / -1;
          }
        }
      `}</style>
    </footer>
  )
}
