// Push #116 — Terms of Service. Server-rendered, no client JS,
// statically prerendered at build time.

import type { Metadata } from 'next'
import Link from 'next/link'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Terms of Service — ShortsForgeAI',
  description:
    'Terms governing your use of ShortsForgeAI, including acceptable use, AI-generated content, payments, refunds, and limitation of liability.',
}

export default function TermsPage() {
  return (
    <>
      <main
        style={{
          minHeight: '100vh',
          background: '#020D0A',
          color: '#F5F7FF',
          fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
          padding: '24px 20px 32px',
        }}
      >
        <div style={{ maxWidth: 760, margin: '0 auto' }}>
          <Link
            href="/"
            style={{
              display: 'inline-block',
              marginBottom: 24,
              fontSize: '0.8rem',
              fontWeight: 700,
              color: '#94A3B8',
              textDecoration: 'none',
            }}
          >
            ← Back to Home
          </Link>
          <h1
            style={{
              fontSize: 'clamp(1.6rem, 4vw, 2.2rem)',
              fontWeight: 900,
              letterSpacing: '-0.02em',
              margin: 0,
              marginBottom: 6,
            }}
          >
            Terms of Service
          </h1>
          <p style={{ color: '#94A3B8', fontSize: 13, margin: 0, marginBottom: 28 }}>
            Last updated: May 2026
          </p>

          <Section title="1. Acceptance">
            By creating an account or using ShortsForgeAI (&ldquo;the
            Service&rdquo;) you agree to these Terms. If you don&apos;t
            agree, please don&apos;t use the Service.
          </Section>

          <Section title="2. Acceptable use">
            You may use the Service to generate AI short-form videos for
            lawful, personal or commercial purposes. You may not use the
            Service to generate content that is illegal, defamatory,
            harassing, or that infringes third-party rights — including
            deepfakes of identifiable people without consent, copyrighted
            material you don&apos;t own, or content depicting minors in any
            unsafe context.
          </Section>

          <Section title="3. AI-generated content">
            Videos produced by the Service are generated by AI models and
            stock-footage libraries. Output may contain inaccuracies, and
            you are responsible for reviewing each generated video before
            publishing. You retain ownership of the videos you generate,
            and you grant us a limited license to store and process them
            to deliver the Service.
          </Section>

          <Section title="4. Payments, trials and refunds">
            Paid subscriptions include a 7-day free trial unless stated
            otherwise. After the trial ends, your card is charged the
            first-month price shown in checkout, and then the regular
            monthly price on each renewal until you cancel. You can
            cancel anytime from your account settings. We honor a 7-day
            money-back guarantee on the first paid month — email{' '}
            <a
              href="mailto:support@shortsforgeai.com"
              style={{ color: '#22D3EE', textDecoration: 'none' }}
            >
              support@shortsforgeai.com
            </a>{' '}
            within 7 days of the first charge and we&apos;ll refund 100%.
            Failed generations never consume credits.
          </Section>

          <Section title="5. Intellectual property">
            The Service, its codebase, brand, and underlying models are
            owned by us or licensed to us. You may not copy, resell or
            redistribute the Service itself. Your generated videos and
            the prompts you write belong to you.
          </Section>

          <Section title="6. Limitation of liability">
            The Service is provided &ldquo;as is&rdquo; without warranty
            of any kind. To the maximum extent permitted by law, our
            total liability for any claim arising from your use of the
            Service is limited to the amount you paid us in the 12
            months preceding the claim. We are not liable for indirect
            or consequential damages, including lost revenue from
            published videos.
          </Section>

          <Section title="7. Changes">
            We may update these Terms from time to time. Material changes
            will be announced in-app or by email at least 14 days before
            they take effect. Continued use after the effective date
            constitutes acceptance.
          </Section>

          <Section title="8. Contact">
            Questions about these Terms?{' '}
            <a
              href="mailto:support@shortsforgeai.com"
              style={{ color: '#22D3EE', textDecoration: 'none' }}
            >
              support@shortsforgeai.com
            </a>
            .
          </Section>
        </div>
      </main>
      <Footer />
    </>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 24 }}>
      <h2
        style={{
          fontSize: '1rem',
          fontWeight: 900,
          letterSpacing: '-0.01em',
          margin: 0,
          marginBottom: 8,
        }}
      >
        {title}
      </h2>
      <p
        style={{
          fontSize: '0.92rem',
          color: '#CBD5E1',
          lineHeight: 1.65,
          margin: 0,
        }}
      >
        {children}
      </p>
    </section>
  )
}
