'use client'

// Push #076 — Standalone /pricing page (real route, not just an anchor).
// Mirrors the Cyber Blue theme used by HomePageClient.
//
// Push #097 — added launch-offer banner with live countdown, a "Most
// Popular" badge on Basic, and a cancel/instant-access/money-back trust
// row directly under the plan cards. The countdown is a UX/urgency
// device; the underlying Stripe discount is the open 50%-off-first-month
// launch offer.

import Link from 'next/link'
import React, { useEffect, useState } from 'react'
import { trackCheckoutClick } from '@/lib/trackClick'
import ExitIntentOffer from '@/components/ExitIntentOffer'

// Push #099 — FAQ entries shown below the pricing comparison table. Pure
// content array so the accordion renders from one source of truth.
const FAQS: { q: string; a: string }[] = [
  {
    q: 'Do I need a credit card to start?',
    a: 'Yes, a card is required to subscribe. You are charged immediately upon signup. Starter is $9.90/month, Creator is $19.90/month, and Studio is $37.90/month.',
  },
  {
    q: 'How fast are videos generated?',
    a: 'Each AI video renders in about 3–5 minutes. We use AI to write, voice, and edit everything automatically.',
  },
  {
    q: 'Can I cancel anytime?',
    a: 'Yes, cancel from your account settings at any time. No contracts, no commitments.',
  },
  {
    q: 'Is there a money-back guarantee?',
    a: 'Yes — both Basic and Pro come with a 7-day money-back guarantee. If you\'re not satisfied, email us within 7 days of your purchase and we\'ll refund 100%. No questions asked.',
  },
  {
    q: 'What happens if a video fails to generate?',
    a: 'Your credits are refunded automatically, the moment the render fails — no support ticket needed. You only ever pay for videos you actually receive.',
  },
  {
    q: 'What’s the difference between AI Generated and Cinematic AI?',
    a: 'AI Generated uses the Seedance engine (great quality, 40 credits/video) and is available on Creator and Studio. Cinematic AI uses the premium Kling engine for top-tier cinematic motion (90 credits/video) and is exclusive to the Studio plan. Starter uses the Fast engine: smart stock footage, 1 credit/video.',
  },
  {
    q: 'How do credits work?',
    a: 'An AI Generated video (Seedance) uses 40 credits. A Cinematic AI video (Kling) uses 90 credits. Creator includes 240 credits/month; Studio includes 400 credits/month and unlocks Cinematic AI. Credits reset each month (no rollover).',
  },
]

// Push #267 — removed Free card. Pricing page now shows only paid plans.
// Free tier still exists for new signups via /signup, but is not shown here
// to avoid users exploiting the $0 entry point.
// Push #339 — added Starter plan at $2.90/mo (15 credits).
function buildPricing() {
  // Push #404 — 3 plans: Starter (Fast) · Creator (Seedance, popular) · Studio (Kling).
  return [
    {
      tier: 'starter',
      name: 'Starter',
      price: '$9.90',
      priceSub: '/ month',
      tagline: '50 videos/month with smart stock footage + AI voiceover.',
      features: [
        '⚡ 50 Fast videos/month',
        'Smart stock footage matched per scene',
        'AI writes script + voiceover',
        'Auto-captions pipeline',
        'Download watermark-free MP4',
        'My Videos history',
      ],
      cta: { label: 'Get Started', href: '#checkout' },
    },
    {
      tier: 'basic',
      name: 'Creator',
      price: '$19.90',
      priceSub: '/ month',
      tagline: '240 credits/month — about 6 fully AI-generated videos (Seedance engine).',
      features: [
        '✨ 240 credits/mo → ~6 AI-generated videos (Seedance)',
        'Every scene generated by AI',
        'AI writes script + voiceover',
        'Auto-captions pipeline',
        'Download watermark-free MP4',
        'My Videos history',
      ],
      cta: { label: 'Get Started', href: '#checkout' },
      highlight: true,
      popular: true,
    },
    {
      tier: 'pro',
      name: 'Studio',
      price: '$37.90',
      priceSub: '/ month',
      // KINEO-STUDIO-400-2026-07-06 — Studio's extra value: 400 credits (vs
      // Creator's 240), the exclusive Kling cinematic engine at 1080p, priority
      // render queue, and premium voices. Copy aligned to the 400-credit grant.
      tagline: 'Cinematic quality — our best AI engine. 400 credits/month (vs Creator\'s 240) + the cinematic Kling engine at 1080p, priority render queue — about 6 premium videos, or up to 10 with Seedance.',
      features: [
        '🎬 ~6 cinematic AI videos/mo (Kling) — Studio only',
        '67% more credits than Creator (400 vs 240/mo)',
        '➕ Or stretch credits to ~10 Seedance videos/mo',
        '⚡ Priority render queue + premium voices',
        'Highest visual quality + motion',
        'AI writes script + voiceover',
        'Auto-captions pipeline',
        'Download watermark-free MP4',
        'My Videos history',
      ],
      cta: { label: 'Get Started', href: '#checkout' },
    },
  ]
}

function trackPricingEvent(name: string): void {
  try {
    void fetch('/api/events', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        event_name: name,
        name,
        path: typeof window !== 'undefined' ? window.location?.pathname : undefined,
      }),
      keepalive: true,
    }).catch(() => {})
  } catch {
    // ignore
  }
}

export default function PricingPage() {
  // Push #077 — pricing card selected state. Pro is selected by default.
  const [selectedPlan, setSelectedPlan] = useState<'starter' | 'basic' | 'pro' | null>('pro')

  // Push #099 — open FAQ index for the accordion (null = all collapsed). First
  // question is open by default so the section reads as scannable, not empty.
  const [openFaq, setOpenFaq] = useState<number | null>(0)
  // Push #114 — CTA state. `purchasing` is the tier whose button shows
  // "Loading…" while the API call is in flight; `checkoutError` surfaces
  // any server-returned error below the cards.
  const [purchasing, setPurchasing] = useState<'starter' | 'basic' | 'pro' | null>(null)
  const [checkoutError, setCheckoutError] = useState<string | null>(null)
  // Push #171 — show a friendly "already subscribed" info banner instead of
  // silently redirecting to /generate when the API blocks a duplicate purchase.
  const [alreadySubscribed, setAlreadySubscribed] = useState(false)
  // Push #116 — ROI calculator slider. Default starts at 5 Shorts/week
  // (a credible "I post often" cadence) so the math reads as meaningful
  // from the first paint.
  const [shortsPerWeek, setShortsPerWeek] = useState<number>(5)
  // Push #117 — sticky mobile CTA bar shows after 300px scroll so phone
  // users always have the "Basic / Pro" choice in reach without
  // scrolling back up to the cards.
  const [showStickyCta, setShowStickyCta] = useState<boolean>(false)

  // #381 — monthly vs annual billing toggle. Annual ≈ 2 months free.
  const [billing, setBilling] = useState<'monthly' | 'annual'>('monthly')
  const ANNUAL: Record<string, { total: string; perMonth: string }> = {
    starter: { total: '$99', perMonth: '$8.25' },
    basic: { total: '$199', perMonth: '$16.58' },
    pro: { total: '$379', perMonth: '$31.58' },
  }

  // Conversion — exit-intent modal extracted to <ExitIntentOffer />
  // (components/ExitIntentOffer.tsx): Starter Pack rescue offer, once per
  // session, desktop mouseleave + mobile inactivity/scroll-up triggers.

  // Push #173 — iOS Safari blocks window.location.href inside async/await
  // (user gesture chain is severed after the first await). Fix: navigate
  // directly to the GET checkout endpoint which does a server-side 302
  // redirect to Stripe. No fetch(), no await, no gesture breakage.
  function handleBuy(tier: 'starter' | 'basic' | 'pro') {
    setPurchasing(tier)
    const eventName = tier === 'pro' ? 'pro_checkout_clicked' : tier === 'starter' ? 'starter_checkout_clicked' : 'basic_checkout_clicked'
    trackPricingEvent(eventName)
    trackCheckoutClick(tier as 'basic' | 'pro')
    // #457 — TikTok Pixel: InitiateCheckout = purchase intent (warmest retargeting audience)
    try {
      const ttq = (window as unknown as { ttq?: { track: Function } }).ttq
      if (ttq && typeof ttq.track === 'function') ttq.track('InitiateCheckout', { content_name: tier })
    } catch { /* non-blocking */ }
    const billingParam = billing === 'annual' ? '&billing=annual' : ''
    // #453 — forward a ?promo= code (e.g. /pricing?promo=FOUNDING50 from the
    // win-back emails) into checkout so the discount auto-applies on plan click.
    const promo = typeof window !== 'undefined' ? new URLSearchParams(window.location.search).get('promo') : null
    const promoParam = promo ? `&promo=${encodeURIComponent(promo)}` : ''
    window.location.href = `/api/stripe/checkout?tier=${tier}${billingParam}${promoParam}`
  }

  // Push #173 — read checkout_error / already_subscribed from URL params
  // set by the GET checkout handler when it can't create a Stripe session.
  useEffect(() => {
    if (typeof window === 'undefined') return
    const params = new URLSearchParams(window.location.search)
    const err = params.get('checkout_error')
    if (err) setCheckoutError(decodeURIComponent(err))
    if (params.get('already_subscribed') === '1') setAlreadySubscribed(true)
  }, [])

  // Push #117 — show the sticky mobile CTA only after the user scrolls
  // past the hero. We pin the listener to passive so it never blocks
  // scroll on slower phones.
  useEffect(() => {
    if (typeof window === 'undefined') return
    const onScroll = () => {
      setShowStickyCta(window.scrollY > 300)
    }
    onScroll()
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  return (
    <div className="min-h-screen bg-[#000000] text-[#f5f5f7] font-sans">
      {/* Subtle cyber-blue glow */}
      <div
        aria-hidden
        className="pointer-events-none fixed -top-[300px] -right-[200px] h-[800px] w-[800px] rounded-full opacity-[0.07]"
        style={{ background: '#2997ff', filter: 'blur(140px)' }}
      />
      <div
        aria-hidden
        className="pointer-events-none fixed -bottom-[400px] -left-[200px] h-[700px] w-[700px] rounded-full opacity-[0.05]"
        style={{ background: '#2997ff', filter: 'blur(160px)' }}
      />

      {/* ───────── Top Nav (simple) ───────── */}
      <nav className="sticky top-0 z-50 border-b border-white/[0.08] bg-[#161618]/90 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#161618] border border-[#2997ff]/40 text-lg shadow-[0_0_14px_rgba(41,151,255,.35)]">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                <path d="M13 2L3 14h7l-1 8 10-12h-7l1-8z" fill="#2997ff" stroke="#2997ff" strokeWidth="0.5" strokeLinejoin="round" />
              </svg>
            </div>
            <div className="flex flex-col leading-none">
              <span className="text-[15px] font-extrabold tracking-tight text-white">
                Kineo
              </span>
            </div>
          </Link>

          <Link
            href="/"
            className="rounded-lg px-4 py-2 text-sm font-semibold text-[#86868b] hover:text-[#f5f5f7] hover:bg-white/[.04] transition"
          >
            ← Back to Home
          </Link>
        </div>
      </nav>

      {/* ───────── Exit-intent modal (Starter Pack rescue offer) ───────── */}
      <ExitIntentOffer />

      {/* ───────── Pricing ───────── */}
      <section className="relative z-10 mx-auto max-w-5xl px-4 pt-12 pb-16 sm:px-6 sm:pt-16">
        <div className="mb-10 text-center">
          <div className="mb-2 text-[11px] font-extrabold uppercase tracking-[.16em] text-[#2997ff]">
            Pricing
          </div>
          <h1 className="text-balance text-4xl font-black tracking-tight sm:text-5xl text-[#f5f5f7]">
            Real AI video generation from $19.90/mo.
          </h1>
          <p className="mx-auto mt-3 max-w-xl text-[14px] text-[#86868b]">
            Not a re-clipper — Kineo generates the whole Short. <span className="text-[#f5f5f7] font-semibold">Creator is $19.90/mo</span> where Revid &amp; StoryShort charge $39+. Or <span className="text-[#f5f5f7] font-semibold">50 videos for $9.90/mo</span>. Flat price, cancel anytime.
          </p>

          {/* ROBO1-PRICE-2026-06-28 — honest trust row. Replaced the
              unverifiable "300+ Shorts created" + "4.8 / 5 average rating"
              with real, checkable signals: first Short free / no card,
              cancel anytime, and the 7-day money-back guarantee. */}
          <div className="mt-6 flex flex-wrap items-center justify-center gap-x-6 gap-y-2">
            {[
              { icon: '🎬', label: 'First Short free — no card' },
              { icon: '↩️', label: 'Cancel anytime' },
              { icon: '🔒', label: '7-day money-back guarantee' },
            ].map(({ icon, label }) => (
              <div key={label} className="flex items-center gap-1.5 text-[12.5px] font-semibold text-[#86868b]">
                <span>{icon}</span>
                <span>{label}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Push #116 — ROI calculator mini-widget. Maps Shorts/week →
            monthly count and an estimated views-at-500-per-Short floor.
            500 views is a deliberately conservative baseline so the
            promise reads as plausible, not lottery. */}
        <div
          className="mx-auto mb-10 max-w-2xl rounded-2xl border p-5 sm:p-6"
          style={{
            background: 'rgba(255,255,255,.03)',
            borderColor: 'rgba(255,255,255,.08)',
          }}
        >
          <label
            htmlFor="roi-slider"
            className="block text-[12px] font-bold text-[#f5f5f7] mb-3"
          >
            How many Shorts per week do you want to post?
          </label>
          <div className="flex items-center gap-3">
            <input
              id="roi-slider"
              type="range"
              min={1}
              max={21}
              step={1}
              value={shortsPerWeek}
              onChange={(e) => setShortsPerWeek(Number(e.target.value))}
              className="w-full accent-[#2997ff]"
              style={{ flex: 1 }}
            />
            <div
              className="rounded-lg px-3 py-1 text-[13px] font-black tabular-nums"
              style={{
                background: 'rgba(41,151,255,.10)',
                border: '1px solid rgba(41,151,255,.32)',
                color: '#2997ff',
                minWidth: 64,
                textAlign: 'center',
              }}
            >
              {shortsPerWeek}/wk
            </div>
          </div>
          <p className="mt-4 text-[13.5px] text-[#f5f5f7] leading-snug">
            At <strong className="text-[#2997ff]">{shortsPerWeek}</strong> Shorts/week →{' '}
            <strong className="text-[#2997ff]">{(shortsPerWeek * 4).toLocaleString()}</strong>{' '}
            Shorts/month → estimated{' '}
            <strong className="text-[#2997ff]">
              {(shortsPerWeek * 4 * 500).toLocaleString()}
            </strong>{' '}
            views/month
          </p>
          <p className="mt-2 text-[12px] font-semibold text-[#86868b]">
            Any plan pays for itself with just 1 viral Short.
          </p>
        </div>

        {/* Push #267 — Free banner removed with Free card */}

        {/* #381 — monthly / annual billing toggle */}
        <div className="mb-7 flex items-center justify-center">
          <div className="inline-flex items-center gap-1 rounded-full border border-white/10 bg-white/[0.04] p-1">
            <button
              type="button"
              onClick={() => setBilling('monthly')}
              className={`rounded-full px-4 py-1.5 text-[13px] font-extrabold transition ${
                billing === 'monthly' ? 'bg-[#2997ff] text-white' : 'text-[#86868b] hover:text-white'
              }`}
            >
              Monthly
            </button>
            <button
              type="button"
              onClick={() => setBilling('annual')}
              className={`flex items-center gap-2 rounded-full px-4 py-1.5 text-[13px] font-extrabold transition ${
                billing === 'annual' ? 'bg-[#2997ff] text-white' : 'text-[#86868b] hover:text-white'
              }`}
            >
              Annual
              <span className="rounded-full bg-[#2997ff]/20 px-2 py-0.5 text-[10px] font-black text-[#2997ff]">
                2 MONTHS FREE
              </span>
            </button>
          </div>
        </div>

        {/* ROBO1-PRICE-2026-06-28 — free-first nudge + honest FOUNDING50
            urgency directly above the plans. The discount % and seat count
            mirror /founding (first 10 members, 50% off locked for life);
            no fake countdown. The free-first line lowers the commitment by
            reminding visitors they can try before they ever pay. */}
        <div
          className="mx-auto mb-7 max-w-2xl rounded-2xl px-5 py-4 text-center"
          style={{ background: 'rgba(41,151,255,0.07)', border: '1px solid rgba(41,151,255,0.4)' }}
        >
          <p className="text-[13.5px] font-extrabold text-[#f5f5f7]">
            🔑 Founding offer — the first <span style={{ color: '#2997ff' }}>10 members</span> lock <span style={{ color: '#2997ff' }}>50% off for life</span>.
          </p>
          <p className="mt-1.5 text-[12.5px] font-semibold text-[#86868b]">
            Not sure yet? <Link href="/signup" className="font-bold text-[#2997ff] hover:text-[#2997ff]">Make your first Short free</Link> — no credit card needed.
          </p>
        </div>

        {/* ROBO-ENTRY-490 (Joseph aprovou 30/06) — $4.90 one-time Starter Pack
            featured as the lowest-commitment ENTRY OFFER above the monthly
            plans, to win a cheaper first "yes". Position/emphasis only — same
            /api/stripe/checkout?pack=starter and price as the 0-credit modal.
            "No subscription" framing keeps it from cannibalizing the subs. */}
        <div className="mx-auto mb-7 max-w-2xl">
          <button
            type="button"
            onClick={() => {
              trackPricingEvent('starter_pack_checkout_clicked')
              window.location.href = '/api/stripe/checkout?pack=starter'
            }}
            className="block w-full rounded-2xl px-5 py-4 text-left transition hover:bg-[rgba(41,151,255,0.10)]"
            style={{ background: 'rgba(41,151,255,0.07)', border: '1px solid rgba(41,151,255,0.5)', boxShadow: '0 0 28px rgba(41,151,255,0.10)', cursor: 'pointer' }}
          >
            <span className="mb-1.5 inline-block rounded-full px-2.5 py-0.5 text-[10px] font-black uppercase tracking-[.12em]" style={{ background: 'rgba(41,151,255,0.14)', border: '1px solid rgba(41,151,255,0.4)', color: '#2997ff' }}>
              ⚡ Cheapest way to start
            </span>
            <span className="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1">
              <span className="text-[15.5px] font-black text-[#f5f5f7]">
                Start with 10 Shorts — <span style={{ color: '#2997ff' }}>$4.90</span> one-time
              </span>
              <span className="text-[13px] font-extrabold" style={{ color: '#2997ff' }}>Get 10 Shorts →</span>
            </span>
            <span className="mt-1.5 block text-[12px] font-semibold text-[#86868b]">
              No subscription · credits never expire · the lowest-commitment way to try the engine before picking a monthly plan.
            </span>
          </button>
          {/* PAYPAL-2026-07-06 — one-time pack via PayPal ($4.90 USD) */}
          <button
            type="button"
            onClick={() => {
              trackPricingEvent('starter_pack_paypal_checkout_clicked')
              window.location.href = '/api/paypal/checkout?pack=starter'
            }}
            className="mt-2 block w-full rounded-xl border border-white/[0.08] px-4 py-2 text-center text-[12.5px] font-bold text-[#f5f5f7] transition hover:bg-white/5 hover:border-[#2997ff]/40"
          >
            or get the 10-Short pack with <span style={{ color: '#009cde', fontWeight: 900 }}>Pay</span><span style={{ color: '#2997ff', fontWeight: 900 }}>Pal</span> ($4.90)
          </button>
        </div>

        <div className="grid grid-cols-1 gap-5 md:grid-cols-3 max-w-5xl mx-auto">
          {buildPricing().map((p) => {
            const isPaid = p.tier === 'starter' || p.tier === 'basic' || p.tier === 'pro'
            const isSelected = isPaid && selectedPlan === p.tier
            const ctaLabel = isSelected
              ? p.tier === 'starter' ? 'Continue with Starter' : p.tier === 'basic' ? 'Continue with Creator' : 'Continue with Studio'
              : p.cta.label
            const isExternal = p.cta.href.startsWith('http')
            return (
              <div
                key={p.tier}
                role={isPaid ? 'button' : undefined}
                tabIndex={isPaid ? 0 : undefined}
                aria-pressed={isPaid ? isSelected : undefined}
                onClick={() => {
                  if (isPaid) setSelectedPlan(p.tier as 'starter' | 'basic' | 'pro')
                }}
                onKeyDown={(e) => {
                  if (!isPaid) return
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault()
                    setSelectedPlan(p.tier as 'starter' | 'basic' | 'pro')
                  }
                }}
                className={`group relative flex flex-col rounded-2xl border p-6 transition-all duration-200 ${
                  // Conversion — Pro always first on all screen sizes.
                  // buildPricing() already returns Pro first; the order
                  // class here is a no-op safety net.
                  ''
                } ${
                  isPaid ? 'cursor-pointer' : ''
                } ${
                  isSelected
                    ? 'border-2 border-[#2997ff] bg-[#1d1d1f] shadow-[0_0_28px_rgba(41,151,255,0.3)]'
                    : p.highlight
                      ? 'border-[#2997ff] bg-[#161618] shadow-[0_0_30px_rgba(41,151,255,0.15)] hover:border-[#2997ff] hover:bg-[rgba(41,151,255,0.06)] hover:shadow-[0_0_20px_rgba(41,151,255,0.18)]'
                      : 'border-white/[0.08] bg-[#161618] hover:border-[#2997ff] hover:bg-[rgba(41,151,255,0.06)] hover:shadow-[0_0_20px_rgba(41,151,255,0.18)]'
                }`}
              >
                {/* Push #116 — Pro now carries the amber "MOST POPULAR"
                    flag instead of the blue "Best Value" pill. Popular
                    takes precedence when both are set so we don't paint
                    two stacked badges. */}
                {p.popular && !isSelected ? (
                  <div
                    className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-[.12em]"
                    style={{
                      background: 'rgba(41,151,255,.15)',
                      border: '1px solid rgba(41,151,255,.4)',
                      color: '#2997ff',
                      boxShadow: '0 4px 18px rgba(41,151,255,.25)',
                    }}
                  >
                    🔥 Most Popular
                  </div>
                ) : p.highlight && !isSelected ? (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-[#2997ff] px-3 py-1 text-[10px] font-black uppercase tracking-[.12em] text-white shadow-[0_4px_18px_rgba(41,151,255,.45)]">
                    Best Value
                  </div>
                ) : null}
                {isSelected && (
                  <div className="absolute -top-3 right-4 flex h-7 w-7 items-center justify-center rounded-full bg-[#22C55E] text-white shadow-[0_4px_14px_rgba(34,197,94,.45)]" aria-label="Selected">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                      <path d="M5 13l4 4L19 7" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                  </div>
                )}
                <div className="text-[11px] font-extrabold uppercase tracking-[.14em] text-[#86868b]">
                  {p.name}
                </div>
                <div className="mt-2 flex items-baseline gap-1.5">
                  <span className="text-[2.4rem] font-black leading-none tracking-tight text-[#f5f5f7]">
                    {billing === 'annual' && ANNUAL[p.tier] ? ANNUAL[p.tier].perMonth : p.price}
                  </span>
                </div>
                <div className="mt-1 text-[12.5px] font-semibold text-[#2997ff]">
                  {billing === 'annual' && ANNUAL[p.tier]
                    ? `/ month · billed annually (${ANNUAL[p.tier].total}/yr)`
                    : p.priceSub}
                </div>
                {'tagline' in p && p.tagline && (
                  <p className="mt-2 text-[12px] text-[#86868b] leading-snug">
                    {p.tagline}
                  </p>
                )}
                <ul className="mt-5 mb-6 flex flex-col gap-2.5">
                  {p.features.map((f) => (
                    <li key={f} className="flex items-start gap-2 text-[13.5px] text-[#f5f5f7]">
                      <span className="mt-[3px] text-[#2997ff]">✓</span>
                      <span>{f}</span>
                    </li>
                  ))}
                </ul>
                {/* Push #114 — paid tiers go through /api/stripe/checkout
                    (button + POST) so the route can pick BRL based on
                    x-vercel-ip-country. Free tier keeps the plain anchor
                    to /signup. */}
                {isPaid ? (
                  <button
                    type="button"
                    disabled={purchasing !== null && purchasing !== p.tier}
                    onClick={(e) => {
                      e.stopPropagation()
                      setSelectedPlan(p.tier as 'starter' | 'basic' | 'pro')
                      handleBuy(p.tier as 'starter' | 'basic' | 'pro')
                    }}
                    className={`mt-auto block w-full rounded-xl px-4 py-3 text-center text-[14px] font-extrabold transition disabled:opacity-60 ${
                      p.highlight || isSelected
                        ? 'bg-[#2997ff] text-white shadow-[0_8px_24px_rgba(41,151,255,.4)] hover:bg-[#2997ff] hover:shadow-[0_10px_32px_rgba(41,151,255,.4)]'
                        : 'border border-white/[0.08] text-[#f5f5f7] hover:bg-white/5 hover:border-[#2997ff]/40'
                    }`}
                  >
                    {purchasing === p.tier ? 'Loading…' : `${ctaLabel} →`}
                  </button>
                ) : (
                  <a
                    href={p.cta.href}
                    target={isExternal ? '_blank' : undefined}
                    rel={isExternal ? 'noopener noreferrer' : undefined}
                    onClick={(e) => {
                      e.stopPropagation()
                    }}
                    className={`mt-auto block rounded-xl px-4 py-3 text-center text-[14px] font-extrabold transition ${
                      isSelected
                        ? 'bg-[#2997ff] text-white shadow-[0_8px_24px_rgba(41,151,255,.4)] hover:bg-[#2997ff] hover:shadow-[0_10px_32px_rgba(41,151,255,.4)]'
                        : 'border border-white/[0.08] text-[#f5f5f7] hover:bg-white/5 hover:border-[#2997ff]/40'
                    }`}
                  >
                    {ctaLabel} →
                  </a>
                )}
                {/* PAYPAL-2026-07-06 — alternate rail for international buyers
                    (US audit 06/07: USD abandoners want a no-card option).
                    Same GET-redirect pattern as handleBuy, zero Stripe changes.
                    USD-only — PayPal converts for the buyer. */}
                {isPaid && (
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation()
                      trackPricingEvent(`${p.tier}_paypal_checkout_clicked`)
                      const billingParam = billing === 'annual' ? '&billing=annual' : ''
                      window.location.href = `/api/paypal/checkout?tier=${p.tier}${billingParam}`
                    }}
                    className="mt-2 block w-full rounded-xl border border-white/[0.08] px-4 py-2 text-center text-[12.5px] font-bold text-[#f5f5f7] transition hover:bg-white/5 hover:border-[#2997ff]/40"
                  >
                    or pay with <span style={{ color: '#009cde', fontWeight: 900 }}>Pay</span><span style={{ color: '#2997ff', fontWeight: 900 }}>Pal</span> (USD)
                  </button>
                )}
                {/* Marker: KINEO-CHECKOUT-TRUST-2026-07-05 — trust cues at the buy button (billed by Kineo after Stripe name fix) */}
                {isPaid && (
                  <p className="mt-2 text-center text-[12px] font-semibold text-[#86868b]">
                    🔒 Secure Stripe checkout · billed by Kineo · cancel anytime · 7-day money-back
                  </p>
                )}
              </div>
            )
          })}
        </div>

        {/* ROBO-ENTRY-490 — the one-time $4.90 Starter Pack was moved UP to a
            featured entry offer above the plans; the duplicate secondary button
            that used to sit here was removed to avoid a repeated adjacent CTA. */}

        {/* Brazilian Pix (Mercado Pago) — one-time credit packs in Real. Runs
            alongside Stripe; for the BR public (Perrengue Chique). */}
        <div className="mx-auto mt-4 max-w-2xl">
          <div
            className="rounded-2xl px-5 py-4 text-center"
            style={{ background: 'rgba(41,151,255,0.06)', border: '1px dashed rgba(41,151,255,0.45)' }}
          >
            <span className="block text-[14px] font-extrabold text-[#f5f5f7]">
              🇧🇷 No Brasil? Pague no <span style={{ color: '#2997ff' }}>Pix</span>
            </span>
            <span className="mt-1 mb-3 block text-[12px] font-semibold text-[#86868b]">
              Pagamento único · sem assinatura · créditos não expiram
            </span>
            <div className="flex flex-col sm:flex-row justify-center gap-2">
              <button
                type="button"
                onClick={() => { trackPricingEvent('mp_pix_checkout_clicked'); window.location.href = '/api/mercadopago/checkout?pack=br50' }}
                className="rounded-xl px-4 py-3 text-[13px] font-extrabold text-white"
                style={{ background: '#2997ff', cursor: 'pointer' }}
              >
                R$50 = 90 créditos (3 AI Gen) →
              </button>
              <button
                type="button"
                onClick={() => { trackPricingEvent('mp_pix_checkout_clicked'); window.location.href = '/api/mercadopago/checkout?pack=br90' }}
                className="rounded-xl px-4 py-3 text-[13px] font-extrabold"
                style={{ background: 'rgba(255,255,255,.06)', border: '1px solid rgba(255,255,255,.12)', color: '#f5f5f7', cursor: 'pointer' }}
              >
                R$90 = 180 créditos (6 AI Gen) →
              </button>
            </div>
          </div>
        </div>

        {/* Push #114 — surface any checkout error inline so users aren't
            stranded silently when the API rejects the request. */}
        {checkoutError && (
          <p className="mx-auto mt-4 max-w-2xl text-center text-[13px] font-semibold text-[#f87171]">
            {checkoutError}
          </p>
        )}

        {/* Push #171 — "already subscribed" info banner. Shown instead of
            the old silent redirect so users understand their plan is active. */}
        {alreadySubscribed && (
          <div className="mx-auto mt-4 max-w-2xl rounded-xl border border-[#2997ff]/30 bg-[#2997ff]/[0.07] px-5 py-4 text-center">
            <p className="text-[13px] font-bold text-[#2997ff]">
              ✅ You already have an active subscription!
            </p>
            <p className="mt-1 text-[12px] text-[#86868b]">
              Your plan is active. If your credits look low, they may still be syncing.
            </p>
            <a
              href="/generate"
              className="mt-3 inline-block rounded-lg bg-[#2997ff] px-5 py-2 text-[13px] font-extrabold text-white shadow-[0_4px_14px_rgba(41,151,255,.35)] transition hover:bg-[#2997ff]"
            >
              Go to Dashboard →
            </a>
          </div>
        )}

        {/* Push #097 — Guarantee row directly under the plan cards.
            Reinforces buyer confidence between the CTA and the comparison
            table below. */}
        <div className="mx-auto mt-6 flex max-w-3xl flex-wrap items-center justify-center gap-x-6 gap-y-2 text-[13.5px] font-bold text-[#f5f5f7]">
          <span className="inline-flex items-center gap-1.5">
            <span className="text-[#2997ff]">✓</span> Cancel anytime
          </span>
          <span className="inline-flex items-center gap-1.5">
            <span className="text-[#2997ff]">✓</span> Instant access
          </span>
          <span className="inline-flex items-center gap-1.5">
            <span className="text-[#2997ff]">✓</span> 7-day money-back guarantee
          </span>
        </div>

        {/* ROBO1-PRICE-2026-06-28 — replaced three fabricated 5-star
            testimonials (invented names + invented view/subscriber numbers)
            with honest "what you actually get" cards. Same spot, same job:
            answer "does this really work?" before the comparison table —
            but with real product facts instead of fake proof. */}
        <div className="mx-auto mt-8 grid max-w-4xl gap-3 sm:grid-cols-3">
          {[
            {
              icon: '🎬',
              title: 'A finished Short, per idea',
              body: 'One topic in → hook, script, AI voice, captions and B-roll out. Built deliberately for that idea, not re-clipped from a long video.',
            },
            {
              icon: '🆓',
              title: 'Try before you pay',
              body: 'Your first Short is free with no credit card. See the real output for yourself, then pick a plan only if it earns it.',
            },
            {
              icon: '📲',
              title: 'Ready to post anywhere',
              body: '9:16 vertical, ~60s, watermark-free MP4 — download and upload straight to YouTube Shorts, TikTok and Reels.',
            },
          ].map((c) => (
            <div
              key={c.title}
              className="rounded-2xl p-4"
              style={{
                background: 'rgba(255,255,255,.03)',
                border: '1px solid rgba(255,255,255,.06)',
              }}
            >
              <div className="text-[18px] mb-2" aria-hidden>
                {c.icon}
              </div>
              <p className="text-[13.5px] font-bold text-[#f5f5f7] leading-snug mb-1.5">
                {c.title}
              </p>
              <p className="text-[12.5px] text-[#86868b] leading-snug">
                {c.body}
              </p>
            </div>
          ))}
        </div>

        {/* Push #087 — feature comparison table. Makes the Fast vs.
            Cinematic split explicit so users understand exactly what
            they're paying for at each tier. Scrolls horizontally on
            small viewports so the table never breaks layout. */}
        <div className="mt-16">
          <div className="mb-6 text-center">
            <div className="mb-2 text-[11px] font-extrabold uppercase tracking-[.16em] text-[#2997ff]">
              Compare plans
            </div>
            <h2 className="text-balance text-2xl font-black tracking-tight sm:text-3xl text-[#f5f5f7]">
              What you get at each tier
            </h2>
          </div>

          <div className="overflow-x-auto rounded-2xl border border-white/[0.08] bg-[#161618]">
            <table className="w-full min-w-[700px] text-left text-[13.5px]">
              <thead>
                <tr className="border-b border-white/[0.08]">
                  <th className="px-5 py-4 text-[11px] font-extrabold uppercase tracking-[.14em] text-[#86868b]">
                    Feature
                  </th>
                  <th className="px-5 py-4 text-center text-[11px] font-extrabold uppercase tracking-[.14em] text-[#86868b]">
                    Free
                  </th>
                  <th className="px-5 py-4 text-center text-[11px] font-extrabold uppercase tracking-[.14em] text-[#86868b]">
                    Starter
                  </th>
                  <th className="px-5 py-4 text-center text-[11px] font-extrabold uppercase tracking-[.14em] text-[#86868b]">
                    Creator
                  </th>
                  <th className="px-5 py-4 text-center text-[11px] font-extrabold uppercase tracking-[.14em] text-[#2997ff]">
                    Studio
                  </th>
                </tr>
              </thead>
              <tbody>
                {[
                  // #409 — table rebuilt for the 3-tier ladder (was still 2-plan).
                  {
                    label: 'Fast videos (smart stock, 1 cr)',
                    free: '✅ with credits',
                    starter: '✅ 50/mo',
                    basic: '✅',
                    pro: '✅',
                  },
                  {
                    label: 'AI Generated videos (Seedance, 30 cr)',
                    free: '✅ 1 free',
                    starter: '—',
                    basic: '✅',
                    pro: '✅',
                  },
                  {
                    label: 'Cinematic AI videos (Kling, 45 cr)',
                    free: '—',
                    starter: '—',
                    basic: '—',
                    pro: '✅ Included',
                  },
                  {
                    label: 'Monthly credits',
                    free: '2 Fast videos',
                    starter: '50',
                    basic: '240',
                    pro: '400',
                  },
                  {
                    label: 'Render time',
                    free: '~3-5 min',
                    starter: '~60 sec',
                    basic: '~3-5 min',
                    pro: '~3-5 min',
                  },
                  {
                    label: 'Watermark-free MP4',
                    free: '—',
                    starter: '✅',
                    basic: '✅',
                    pro: '✅',
                  },
                  {
                    label: 'Priority support',
                    free: '—',
                    starter: 'Email',
                    basic: 'Email',
                    pro: 'Priority',
                  },
                ].map((row) => (
                  <tr key={row.label} className="border-b border-white/[0.04] last:border-0">
                    <td className="px-5 py-3.5 font-semibold text-[#f5f5f7]">{row.label}</td>
                    <td className="px-5 py-3.5 text-center text-[#86868b]">{row.free}</td>
                    <td className="px-5 py-3.5 text-center text-[#86868b]">{row.starter}</td>
                    <td className="px-5 py-3.5 text-center text-[#86868b]">{row.basic}</td>
                    <td className="px-5 py-3.5 text-center font-bold text-[#2997ff]">{row.pro}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <p className="mt-4 text-center text-[12px] text-[#86868b]">
            ⚡ Fast (smart stock) is included on every paid plan. ✨ AI Generated (Seedance) starts at Creator. 🎬 Cinematic AI (Kling) — our highest quality — is exclusive to Studio.
          </p>
        </div>

        {/* Push #099 — FAQ accordion. Five evergreen objections lifted from
            support tickets and the homepage CRO copy. Pure client-side
            useState toggle so the page stays static-renderable. */}
        <div className="mt-16">
          <div className="mb-6 text-center">
            <div className="mb-2 text-[11px] font-extrabold uppercase tracking-[.16em] text-[#2997ff]">
              FAQ
            </div>
            <h2 className="text-balance text-2xl font-black tracking-tight sm:text-3xl text-[#f5f5f7]">
              💬 Frequently Asked Questions
            </h2>
          </div>

          <div className="mx-auto max-w-2xl overflow-hidden rounded-2xl border border-white/[0.08] bg-[#161618]">
            {FAQS.map((item, i) => {
              const isOpen = openFaq === i
              return (
                <div
                  key={item.q}
                  className="border-b border-white/[0.06] last:border-0"
                >
                  <button
                    type="button"
                    onClick={() => setOpenFaq(isOpen ? null : i)}
                    aria-expanded={isOpen}
                    className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left transition hover:bg-white/[.02]"
                  >
                    <span className="text-[14.5px] font-bold text-[#f5f5f7]">
                      {item.q}
                    </span>
                    <span
                      aria-hidden
                      className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-white/[0.08] text-[#2997ff] transition-transform duration-200 ${
                        isOpen ? 'rotate-45' : ''
                      }`}
                      style={{ fontSize: 16, lineHeight: 1 }}
                    >
                      +
                    </span>
                  </button>
                  {isOpen && (
                    <div className="px-5 pb-4 -mt-1">
                      <p className="text-[13.5px] leading-relaxed text-[#86868b]">
                        {item.a}
                      </p>
                    </div>
                  )}
                </div>
              )
            })}
          </div>

          <p className="mt-5 text-center text-[12.5px] text-[#86868b]">
            Still have questions?{' '}
            <a
              href="mailto:support@shortsforgeai.com"
              className="font-bold text-[#2997ff] hover:text-[#2997ff]"
            >
              Email us →
            </a>
          </p>
        </div>

        {/* Push #116 — explicit 7-day money-back guarantee callout under
            the FAQ. The trust row at the top of the page mentions the
            guarantee in passing; this spells out the terms so the buyer
            who scrolled all the way through gets the reassurance
            without leaving the page. */}
        <div
          className="mx-auto mt-12 max-w-3xl rounded-2xl p-5 sm:p-6"
          style={{
            background: 'rgba(41,151,255,.06)',
            border: '1px solid rgba(41,151,255,.35)',
            boxShadow: '0 0 40px rgba(41,151,255,.10)',
          }}
        >
          <div className="flex items-start gap-3 sm:gap-4">
            <div
              aria-hidden
              style={{
                fontSize: '1.6rem',
                lineHeight: 1,
                flexShrink: 0,
              }}
            >
              🛡️
            </div>
            <div>
              <div className="text-[14px] font-black text-[#f5f5f7] mb-1">
                7-day money-back guarantee — all plans
              </div>
              <p className="text-[13px] text-[#86868b] leading-relaxed m-0">
                If you&apos;re not happy in the first 7 days, email us and we&apos;ll refund 100%. No questions asked. Works for all plans.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Push #117 — spacer so the sticky bar below doesn't cover the
          last bit of the FAQ on mobile. Desktop ignores it. */}
      {showStickyCta && <div aria-hidden className="h-24 md:hidden" />}

      {/* Push #117 — sticky mobile checkout bar. Only renders on
          small viewports (md:hidden), only after 300 px of scroll, and
          uses backdrop-blur + the safe-area class so the bar clears the
          iOS home-indicator. Buttons go through the same handleBuy used
          by the cards above. */}
      {showStickyCta && (
        <div
          className="mobile-sticky-cta md:hidden"
          style={{
            position: 'fixed',
            bottom: 0,
            left: 0,
            right: 0,
            background: 'rgba(10,10,15,0.96)',
            backdropFilter: 'blur(12px)',
            WebkitBackdropFilter: 'blur(12px)',
            borderTop: '1px solid rgba(255,255,255,.08)',
            padding: '12px 16px',
            display: 'flex',
            gap: 8,
            zIndex: 50,
          }}
        >
          {/* #409 — Starter added to the sticky bar (was missing after the 3-tier launch) */}
          <button
            type="button"
            disabled={purchasing !== null && purchasing !== 'starter'}
            onClick={() => handleBuy('starter')}
            style={{
              flex: 1,
              padding: '12px 6px',
              borderRadius: 10,
              background: 'rgba(255,255,255,.06)',
              border: '1px solid rgba(255,255,255,.12)',
              color: '#f5f5f7',
              fontSize: '0.75rem',
              fontWeight: 800,
              cursor: 'pointer',
              minHeight: 48,
            }}
          >
            {purchasing === 'starter' ? 'Loading…' : 'Starter $9.90'}
          </button>
          <button
            type="button"
            disabled={purchasing !== null && purchasing !== 'basic'}
            onClick={() => handleBuy('basic')}
            style={{
              flex: 1,
              padding: '12px 6px',
              borderRadius: 10,
              background: 'rgba(255,255,255,.06)',
              border: '1px solid rgba(255,255,255,.12)',
              color: '#f5f5f7',
              fontSize: '0.75rem',
              fontWeight: 800,
              cursor: 'pointer',
              minHeight: 48,
            }}
          >
            {purchasing === 'basic' ? 'Loading…' : 'Creator $19.90'}
          </button>
          <button
            type="button"
            disabled={purchasing !== null && purchasing !== 'pro'}
            onClick={() => handleBuy('pro')}
            style={{
              flex: 1,
              padding: '12px 8px',
              borderRadius: 10,
              background: '#2997ff',
              color: '#ffffff',
              fontSize: '0.8rem',
              fontWeight: 800,
              cursor: 'pointer',
              minHeight: 48,
              border: 'none',
              boxShadow: '0 8px 22px rgba(41,151,255,.35)',
            }}
          >
            {purchasing === 'pro' ? 'Loading…' : 'Studio $37.90 🔥'}
          </button>
        </div>
      )}

      {/* ───────── Footer ───────── */}
      <footer className="relative z-10 border-t border-white/[0.08]">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 px-4 py-8 sm:flex-row sm:px-6">
          <div className="flex items-center gap-2.5">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#161618] border border-[#2997ff]/40 text-sm">
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                <path d="M13 2L3 14h7l-1 8 10-12h-7l1-8z" fill="#2997ff" />
              </svg>
            </div>
            <span className="text-[13px] font-bold text-[#f5f5f7]">
              Kineo
            </span>
          </div>
          <p className="text-[11.5px] text-[#86868b]">© 2026 Kineo</p>
        </div>
        {/* Push #116 — legal + contact strip. */}
        <div className="mx-auto flex max-w-6xl flex-wrap items-center justify-center gap-x-3 gap-y-1 px-4 pb-6 sm:px-6">
          <Link href="/terms" className="text-[11.5px] font-medium text-[#86868b] hover:text-[#f5f5f7]">Terms of Service</Link>
          <span aria-hidden className="text-[11.5px] text-[#86868b] opacity-40">·</span>
          <Link href="/privacy" className="text-[11.5px] font-medium text-[#86868b] hover:text-[#f5f5f7]">Privacy Policy</Link>
          <span aria-hidden className="text-[11.5px] text-[#86868b] opacity-40">·</span>
          <a href="mailto:support@shortsforgeai.com" className="text-[11.5px] font-medium text-[#86868b] hover:text-[#f5f5f7]">Contact</a>
        </div>
      </footer>
    </div>
  )
}
